### PR TITLE
refactor: update year in splash copyright notice

### PR DESCRIPTION
**Pull request by florianesser**

### CODE REVIEW

**Review by stempler — APPROVED** [review]

**Comment by emanuelaepure10** [comment]
@florianesser Should I cherry pick this commit into the release branch and update the installers?
Thank you

**Comment by florianesser** [comment]
> Should I cherry pick this commit into the release branch and update the installers?

@emanuelaepure10 No, releases shouldn't be changed retroactively. It's fine, though, it will be part of the next release.

**Comment by emanuelaepure10** [comment]
@florianesser I interpreted it as an acceptance by merging of [this PR](https://github.com/halestudio/hale/pull/1118)
I apologize; I realize I should have waited for a written response to my question. This serves as a valuable lesson for the future.

**Comment by florianesser** [comment]
> I apologize; I realize I should have waited for a written response to my question. This serves as a valuable lesson for the future.

@emanuelaepure10  No worries! I hadn't seen that Simon had already signed off on the PR to update the `release` branch when I added my comment here.

**Comment by stempler** [comment]
@florianesser I saw no harm in merging that to release since it only affects the splash screen and nothing else, especially no headless artifacts.

**Pull request merged**
