### PR TITLE
Remove GeoServer App-Schema plug-in from HALE core

### PR DESCRIPTION
**Pull request by ridethepenguin**
This PR removes the App-Schema plug-in from the HALE's code base. Besides removing the plug-in's own projects, it was necessary to refactor the XtraServer plug-in, which depended on the App-Schema plug-in itself.

The final goal here is to move the App-Schema plug-in source code to a separate repo, to allow the plug-in's maintainers greater freedom in determining its release cycle. Users of the plug-in will have to download it separately from a yet-to-be-published web site, hosted by [GeoSolutions](https://www.geo-solutions.it/), and install it in their own HALE product (it will be a matter of uncompressing a ZIP archive inside HALE's installation folder).

Somewhat related forum discussion is [here](https://discuss.wetransform.to/#/thread/i15b/Installing-new-features-from-remote-p2-update-sites).

Another PR targeted to the [hale-platform](https://github.com/halestudio/hale-platform) project will follow.

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: bc46be2199f0a94e29e4d009093b012fbc830696
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/halestudio/hale

---
This message was auto-generated by https://gitcop.com

**Comment by stempler** [comment]
Can one of the admins verify this patch?

**Comment by stempler** [comment]
ok to test

**Comment by ridethepenguin** [comment]
@florianesser Thanks for fixing the commit message! Sorry for not acting promptly to your request.

**Comment by florianesser** [comment]
@ridethepenguin No worries! I hadn't realized that I could update the commit message myself when I posted my comment, but @stempler reminded me 😃

**Pull request merged**
