### PR TITLE
Upgrade Eclipse platform to Photon

### PR DESCRIPTION
**Pull request by florianesser**
Updates the Eclipse platform to v4.8 (Photon). See also #631.

The `HALE` and `Tests` products validate and run on a Java 8 JDK in Eclipse Photon. There shouldn't be any compile errors in Eclipse.

~The target platform is not yet mirrored, the P2 repositories at download.eclipse.org are used in the meantime.~

Due to a problem w/ the current preview build of groovy-eclipse 3.0.0 for the Photon platform, constructors for Groovy classes w/ the `@Immutable` annotations cannot be used by Java classes and cause compile errors in Eclipse (not in the CLI build, though). To work around this, all Java classes that use `@Immutable` Groovy classes were converted to Groovy.

First tests indicate that the upgrade solves the problem with GTK 3 (#53) on current Linux desktops, but this needs some more testing to be sure.

### CODE REVIEW

**Comment by florianesser** [comment]
@stempler I've mirrored the Photon P2 repositories and updated the target platform accordingly. I guess now it's ready to be merged.

**Comment by stempler** [comment]
I created a PR for your PR, which reduces the warnings in the IDE: https://github.com/florianesser/hale/pull/4

**Comment by florianesser** [comment]
@stempler 
- Both the HALE and the Tests product validate for me in Eclipse Photon on Windows
- I didn't notice the `IncompatibleClassChangeError` in my tests yet

**Comment by florianesser** [comment]
Interestingly, I get a different error, but it appears to have the same cause:
```
java.lang.VerifyError: (class: eu/esdihumboldt/hale/ui/service/align/resolver/internal/EntityContentProvider, method: dispose signature: ()V) Illegal use of nonvirtual function call
	at eu.esdihumboldt.hale.ui.service.align.resolver.internal.ViewerEntityTray.createContents(ViewerEntityTray.java:74)
	at org.eclipse.jface.dialogs.TrayDialog.openTray(TrayDialog.java:417)
	at eu.esdihumboldt.hale.ui.service.align.resolver.UserFallbackEntityResolver$2$1.create(UserFallbackEntityResolver.java:261)
	at org.eclipse.jface.window.Window.open(Window.java:783)
	at eu.esdihumboldt.hale.ui.service.align.resolver.UserFallbackEntityResolver$2.run(UserFallbackEntityResolver.java:266)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:37)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:182)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:3906)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3537)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.block(ModalContext.java:165)
	at org.eclipse.jface.operation.ModalContext.run(ModalContext.java:369)
	at org.eclipse.jface.dialogs.ProgressMonitorDialog.run(ProgressMonitorDialog.java:471)
	at eu.esdihumboldt.hale.ui.util.io.ThreadProgressMonitor$2.run(ThreadProgressMonitor.java:134)
	at org.eclipse.swt.widgets.Synchronizer.syncExec(Synchronizer.java:233)
	at org.eclipse.ui.internal.UISynchronizer.syncExec(UISynchronizer.java:144)
	at org.eclipse.swt.widgets.Display.syncExec(Display.java:4567)
	at eu.esdihumboldt.hale.ui.util.io.ThreadProgressMonitor.runWithProgressDialog(ThreadProgressMonitor.java:129)
	at eu.esdihumboldt.hale.ui.service.project.ProjectResourcesUtil.executeProvider(ProjectResourcesUtil.java:227)
	at eu.esdihumboldt.hale.ui.service.project.ProjectResourcesUtil.executeProvider(ProjectResourcesUtil.java:159)
	at eu.esdihumboldt.hale.ui.service.project.internal.ProjectServiceImpl.load(ProjectServiceImpl.java:616)
	at eu.esdihumboldt.hale.ui.service.project.RecentProjectsMenu$MenuItemSelectionListener.widgetSelected(RecentProjectsMenu.java:85)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:249)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:86)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4118)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1052)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:3931)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3534)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1170)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1059)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:153)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:667)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:597)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
	at eu.esdihumboldt.hale.ui.application.Application.run(Application.java:116)
	at eu.esdihumboldt.hale.ui.application.Application.run(Application.java:1)
	at eu.esdihumboldt.hale.common.app.AbstractApplication.run(AbstractApplication.java:51)
	at eu.esdihumboldt.hale.common.app.AbstractApplication.start(AbstractApplication.java:33)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:656)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:592)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1498)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1471)
```

**Comment by stempler** [comment]
This PR (https://github.com/florianesser/hale/pull/5) should fix the `IncompatibleClassChangeError`. Seems the Groovy compiler has some problems with multiple super methods in Java 8 (via base class and default methods in interfaces).

> Both the HALE and the Tests product validate for me in Eclipse Photon on Windows

Could this then maybe be cached bundles in your case? A quick check in the hale-build-support repository shows that the entry is there in the manifest, at least for the `concurrent` bundle.
I guess we need a similar setting to [here](https://github.com/halestudio/hale-platform/blob/6446c005aba28f030e1c7f1a758acb5a4ca1b8aa/modules/deegree/deegree.gradle#L70) for these bundles.

**Comment by florianesser** [comment]
[This documention] suggests that the specified filter `(&(osgi.ee=JavaSE)(version=1.1))` may be invalid as `JavaSE` is used only from version 1.2 onwards. I don't know why this isn't reported on Windows, though.

> I guess we need a similar setting to here for these bundles.

I could get rid of the validation errors by removing the `Require-Capability` lines from the respective manifests (PRs in `shared-platform` and `hale-platform`).

**Comment by stempler** [comment]
> I could get rid of the validation errors by removing the Require-Capability lines from the respective manifests (PRs in shared-platform and hale-platform).

Great, so I guess after the platform update site update we are done.

**Pull request merged**
