### PR TITLE
remove xtraserver plugin

### PR DESCRIPTION
**Pull request by azahnen**
Migrated to external plugin: https://github.com/interactive-instruments/xtraserver-plugin-for-hale

### CODE REVIEW

**Comment by stempler** [comment]
Can one of the admins verify this patch?

**Comment by florianesser** [comment]
ok to test

**Comment by florianesser** [comment]
@azahnen In case you plan to have a publicly accessible update site for the plugin, we could add that to the default list of software sites in the "Install Software" dialog. Do you plan to set one up?

**Comment by azahnen** [comment]
@florianesser Yes, that is the plan, but it is not set up yet. I will do so in the course of the day and let you know the URL. Thanks for the hint.

**Review by florianesser — APPROVED** [review]
LGTM

**Comment by azahnen** [comment]
@florianesser The URL is https://interactive-instruments.github.io/xtraserver-plugin-for-hale/

**Comment by florianesser** [comment]
Thanks @azahnen, I created a [PR in your fork](https://github.com/interactive-instruments/hale/pull/2) with the required change to include the update site by default.

**Pull request merged**
