### PR TITLE
Contribute 2D map

### PR DESCRIPTION
**Pull request by michel-kraemer**
Hope you like it.

Let me know if you have questions.

I already signed the CLA.

### CODE REVIEW

**Comment by stempler** [comment]
Can one of the admins verify this patch?

**Comment by stempler** [comment]
add to whitelist

**Comment by stempler** [comment]
ok to test

**Comment by stempler** [comment]
test this please

**Comment by stempler** [comment]
retest this please

**Comment by michel-kraemer** [comment]
> Can one of the admins verify this patch?

Dunno if they can but they may.

**Comment by stempler** [comment]
ok to test

**Comment by stempler** [comment]
test this please

**Comment by stempler** [comment]
ok to test

**Comment by stempler** [comment]
LGTM

Thanks a lot, that will surely boost the work on #64!

**Comment by michel-kraemer** [comment]
👍

**Pull request merged**
