### PR TITLE
Add spatial index service

### PR DESCRIPTION
**Pull request by florianesser**
Added a spatial index service based on the use case described in #300.

### CODE REVIEW

**Comment by stempler** [comment]
Regarding the build error - probably the `ext/geom` folder is not picked up for that. You could either add it [here](https://github.com/halestudio/hale/blob/master/build/build.gradle#L94) or move it to `ext/styledmap`.

**Comment by florianesser** [comment]
Ah, thanks! I'll add the folder to the build.gradle then.

**Comment by florianesser** [comment]
retest this please

**Comment by stempler** [comment]
retest this please

**Pull request merged**
