### PR TITLE
Fix "Isolated" checkbox in App-Schema alignment export wizard

### PR DESCRIPTION
**Pull request by florianesser**
See #611

@ridethepenguin @nmco Could you also review this, please?

### CODE REVIEW

**Comment by nmco** [comment]
Thank you @florianesser, the fix looks good to me, I will manually test this Monday with GeoServer.

**Comment by nmco** [comment]
I did a build of this branch and manually tested it:

image

It seems that it is not possible to select \ click the check-box for the isolated workspaces:

image

Please note that I tested this on Linux. Could this be someway related with the OS ?

**Comment by nmco** [comment]
So removing the three commits of this PR, make the check-box selectable ... at least in my environment:

image

**Comment by thorsten-reitz** [comment]
So this is apparently related to the OS - without the fix, it works on Linux, with fix it works on windows. Probably this needs to be refactored so that different code is used in the different builds?

Please note that @florianesser is on vacation and that we discussed on Friday that Geosolutions would take over responsibility for app-schema /hale studio plugin related patches.

**Comment by ridethepenguin** [comment]
@nmco I have manually tested a HALE build from this branch on a native 64-bit Linux box running Fedora 27:

image

...and a 32-bit virtual machine running Windows 7:

image

Works for me in both environments: the checkbox is centered and it is editable. So... not sure what is going on? :-)
I've noticed the revision number I get is not the same as yours: are we building the same code?

image

On a side note: on Linux, I had to force SWT to use GTK2 instead of GTK3, or else I would not be able to open virtually any dialog because of [this bug](https://bugs.eclipse.org/bugs/show_bug.cgi?id=486069); I don't think it's related, but I wanted to mention it for the sake of completeness.

**Comment by nmco** [comment]
@ridethepenguin regarding the revision numbers, I tested this several days ago with a merge of master (like you did) which means my HAED was different for obvious reasons.

Long story short, the issue is still present for me, but forcing HALE to use GTK2 instead of GTk3 fixed the issue for me (export SWT_GTK3=0).

So summarizing:
1. master, works fine for GTK3 but fails on Windows
2. @florianesser fix, works fine for Windows but not for GTK3

I will have to think about the best solution for this.

**Comment by stempler** [comment]
@nmco Could be a similar issue then as in https://github.com/halestudio/hale/issues/53 that the underlying Eclipse/SWT version is just too old for current GTK versions.

**Comment by nmco** [comment]
Thank you for the reference @stempler, so I would say let's go ahead and merge this fix. The workaround GTK3 users are using for the other related issues will work for this one too.

**Pull request merged**
