### PR TITLE
improve xtraserver export

### PR DESCRIPTION
**Pull request by azahnen**

### CODE REVIEW

**Comment by stempler** [comment]
Can one of the admins verify this patch?

**Comment by florianesser** [comment]
ok to test

**Comment by florianesser** [comment]
ok to test

**Comment by florianesser** [comment]
@azahnen Could you take a look at the test failures ([1](https://builds.wetransform.to/job/hale/job/hale%7Epull/919/testReport/junit/eu.esdihumboldt.hale.io.xtraserver.writer/XtraServerMappingFileWriterTest/testWriteArchive/), [2](https://builds.wetransform.to/job/hale/job/hale%7Epull/919/testReport/junit/eu.esdihumboldt.hale.io.xtraserver.writer/XtraServerMappingFileWriterTest/testWriteMappingFile/)) that Jenkins reported?

**Comment by azahnen** [comment]
@florianesser Sorry for that, I pushed a fix.

**Pull request merged**
