### PR TITLE
Use value in .cpg to prefill charset dialog when importing shapefile

### PR DESCRIPTION
**Pull request by florianesser**
see #478

### CODE REVIEW

**Comment by thorsten-reitz** [comment]
The CPG is an optional, but official file for a shapefile, which is a simple ASCII file with the name of the encoding. QGIS for example also writes the CPG file. Much of our data actually contains these.

**Comment by stempler** [comment]
Just wondering where to find such information. The [specification I found](https://www.esri.com/library/whitepapers/pdfs/shapefile.pdf) is probably to old and not complete.

**Comment by thorsten-reitz** [comment]
This article mentioned the file as part of a shapfile: http://desktop.arcgis.com/en/arcmap/10.3/manage-data/shapefiles/shapefile-file-extensions.htm

**Comment by stempler** [comment]
Seems to be more info [here](https://www.loc.gov/preservation/digital/formats/fdd/fdd000280.shtml#specs) as well. Would be interesting to know though if the value is always compatible to the encodings available in Java.
Also, it might make sense to make it a default when reading Shapefiles, not only if loaded in the UI. Maybe Geotools does that already ans we disable the behavior by specifying an explicit encoding.

**Comment by florianesser** [comment]
> Also, it might make sense to make it a default when reading Shapefiles, not only if loaded in the UI. Maybe Geotools does that already and we disable the behavior by specifying an explicit encoding.

Good point, I'll look into that.

**Pull request merged**
